### ISSUE TITLE
Conflicts with lambda-logger but not with n-logger

### ISSUE THREAD

**Issue by GeoffThorpeFT** [Financial-Times/dotcom-reliability-kit#516]
**Node.js version:** v14
**Impacted package(s):** logger

## Steps to reproduce
run this makefile script:
```
testLoggers:
	echo =========================== no loggers ==================================
	npm uninstall @dotcom-reliability-kit/logger
	npm uninstall @financial-times/n-logger
	npm uninstall @financial-times/lambda-logger
	node test-loggers false false false

	echo =========================== lambda-logger ONLY ==================================
	npm uninstall @dotcom-reliability-kit/logger
	npm uninstall @financial-times/n-logger
	npm install @financial-times/lambda-logger
	node test-loggers false false true

	echo =========================== n-logger ONLY ==================================
	npm uninstall @dotcom-reliability-kit/logger
	npm install @financial-times/n-logger
	npm uninstall @financial-times/lambda-logger
	node test-loggers false true false

	echo =========================== n-logger PLUS lambda-logger ==================================
	npm uninstall @dotcom-reliability-kit/logger
	npm install @financial-times/n-logger
	npm install @financial-times/lambda-logger
	node test-loggers false true true

	echo =========================== kit logger ONLY==================================
	npm install @dotcom-reliability-kit/logger
	npm uninstall @financial-times/n-logger
	npm uninstall @financial-times/lambda-logger
	node test-loggers true false false

	echo =========================== kit logger PLUS lambda logger ==================================
	npm install @dotcom-reliability-kit/logger
	npm uninstall @financial-times/n-logger
	npm install @financial-times/lambda-logger
	node test-loggers true false true

	echo =========================== kit logger PLUS n-logger ==================================
	npm install @dotcom-reliability-kit/logger
	npm install @financial-times/n-logger
	npm uninstall @financial-times/lambda-logger
	node test-loggers true true false

	echo =========================== ALL THREE loggers ==================================
	npm install @dotcom-reliability-kit/logger
	npm install @financial-times/n-logger
	npm install @financial-times/lambda-logger
	node test-loggers true true true
```

This is the code for `test-loggers`:
```
const testLoggers = () => {
	const [, , useKitLogger, useNLogger, useLambdaLogger] = process.argv;
	console.log("@@@@@@@ start @@@@@@@@@")
	console.log(useKitLogger, useNLogger, useLambdaLogger);
	if (useKitLogger === 'true') {
		const kitLogger = require('@dotcom-reliability-kit/logger');
		kitLogger.info('kitLogger is being used');
	}
	if (useNLogger === 'true') {
		const nLogger = require('@financial-times/n-logger').default;
		nLogger.info('nLogger is being used');
	}
	if (useLambdaLogger === 'true') {
		const lambdaLogger = require('@financial-times/lambda-logger');
		lambdaLogger.info('lambdaLogger is being used');
	}
	console.log("@@@@@@@ end @@@@@@@@@\n\n\n");
};

testLoggers();
```

## Expected behaviour

All combinations of the loggers work

## Actual result

The new kit logger conflicts with `lambda-logger` and fails to produce kit logger output; instead failing with a `destination.on is not a function` error.

```
echo =========================== ALL THREE loggers ==================================
=========================== ALL THREE loggers ==================================
npm install @dotcom-reliability-kit/logger
npm WARN notsup Unsupported engine for @dotcom-reliability-kit/logger@1.1.2: wanted: {"node":"14.x || 16.x || 18.x","npm":"7.x || 8.x"} (current: {"node":"14.19.3","npm":"6.14.17"})
npm WARN notsup Not compatible with your version of node/npm: @dotcom-reliability-kit/logger@1.1.2
npm WARN notsup Unsupported engine for @dotcom-reliability-kit/app-info@1.2.1: wanted: {"node":"14.x || 16.x || 18.x","npm":"7.x || 8.x"} (current: {"node":"14.19.3","npm":"6.14.17"})
npm WARN notsup Not compatible with your version of node/npm: @dotcom-reliability-kit/app-info@1.2.1
npm WARN notsup Unsupported engine for @dotcom-reliability-kit/serialize-error@1.1.4: wanted: {"node":"14.x || 16.x || 18.x","npm":"7.x || 8.x"} (current: {"node":"14.19.3","npm":"6.14.17"})
npm WARN notsup Not compatible with your version of node/npm: @dotcom-reliability-kit/serialize-error@1.1.4

+ @dotcom-reliability-kit/logger@1.1.2
updated 1 package and audited 687 packages in 6.924s

92 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

npm install @financial-times/n-logger

> @financial-times/n-logger@10.3.1 preinstall /Users/geoff.thorpe/Documents/Repos/dotcom-reliability-kit/node_modules/@financial-times/n-logger
> [ "$INIT_CWD" != "$PWD" ] || npm_config_yes=true npx check-engine

npm WARN notsup Unsupported engine for @financial-times/n-logger@10.3.1: wanted: {"node":"14.x || 16.x || 18.x","npm":"7.x || 8.x"} (current: {"node":"14.19.3","npm":"6.14.17"})
npm WARN notsup Not compatible with your version of node/npm: @financial-times/n-logger@10.3.1

+ @financial-times/n-logger@10.3.1
updated 1 package and audited 687 packages in 3.372s

95 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

npm install @financial-times/lambda-logger
+ @financial-times/lambda-logger@4.0.3
added 29 packages from 22 contributors and audited 716 packages in 4.017s

95 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

node test-loggers true true true
@@@@@@@ start @@@@@@@@@
true true true
[32minfo[39m: nLogger is being used
["2023-04-17T09:54:54.054Z"] INFO  (99727 on FT-MW5769): lambdaLogger is being used
@@@@@@@ end @@@@@@@@@



events.js:377
      throw er; // Unhandled 'error' event
      ^

TypeError: destination.on is not a function
    at start (/Users/geoff.thorpe/Documents/Repos/dotcom-reliability-kit/node_modules/thread-stream/lib/worker.js:63:15)
Emitted 'error' event on ThreadStream instance at:
    at Immediate.<anonymous> (/Users/geoff.thorpe/Documents/Repos/dotcom-reliability-kit/node_modules/thread-stream/index.js:360:12)
    at processImmediate (internal/timers.js:464:21)
make: [testLoggers] Error 1 (ignored)
```

**Comment by rowanmanning** [comment]
Ah I've found the issue!

The Reliability Kit logger doesn't come bundled with pino-pretty, so when it's installed by itself it'll not try to use pino-pretty unless the app also installs it. However lambda-logger _does_ come bundled with pino-pretty. What this results in is interesting because the version it uses is `v2.0.0` whereas Reliability Kit's logger was built with v10+ of pino-pretty in mind.

So without pino-pretty installed by the app, Reliability Kit logger will just break.

This is resolvable by installing pino-pretty as a development dependency in your app, ensuring that you're using the latest version. [See instructions here](https://github.com/Financial-Times/dotcom-reliability-kit/tree/main/packages/logger#local-development-usage). When In tested this locally, the loggers play nicely together.

There's still something here to resolve in Reliability Kit: we probably need to specify a version range required for pino-pretty so that we throw a more useful error if there's a mismatch. I'll think of a way to resolve this.

**Comment by rowanmanning** [comment]
Thanks again for reporting @GeoffThorpeFT, we now have pino-pretty as a peer dependency as of v2.2.0 of the logger so other people will get a warning on `npm install` if they are using an outdated version.
